# This goes with the interactive-podman-ou2024-sh but this might also work with rknop dev?
preloads:
  # - /snpit_env/configs/ou2024_container_config.yaml  # Env variable borken. Rob says this should be
  # ${SNPIT_DEFAULT_CONFIG} but I am waiting on him to fix that functionality.
  - /snpit_env_base/configs/rknop_dev_container_config.yaml

augments:
  - ../../campari/tests/master_test_config.yaml

photometry:
  campari_io:
    output_dir: /scratch/campari_out_dir
    debug_dir: /scratch/campari_debug_dir
    save_debug: true
    test_num: 1
    test_data: /scratch/campari_test_data
    # test_num is a hack suggested by Rob. If you want to save a lc to the database, it needs a provenance.
    # However, if a run successfully creates a provenance but does not successfully complete, the code will fail
    # because it tries to create a provenance that already exists. By iterating this dummy parameter, we can ensure
    # the provenance is new because the hash of this config file will change.
  test_data: /photometry_test_data
