ou24:
  config_file: /pscratch/sd/c/cmeldorf/campari/examples/perlmutter/tds_jupyter.yaml
  sn_truth_dir: /dvs_ro/cfs/cdirs/lsst/www/DESC_TD_PUBLIC/Roman+DESC/PQ+HDF5_ROMAN+LSST_LARGE
  sims_sed_library: /pscratch/sd/c/cmeldorf/rubin_sim_data/sims_sed_library

photometry:
  campari:
    cutout_size: 11
    initial_flux_guess: 3000
    fetch_SED: true
    source_phot_ops: true
    use_roman: true
    weighting: true
    make_initial_guess: true
    method: lsqr
    pixel: false
    subtract_background: true
    use_real_images: true
    save_model: true
    save_debug: true
    psfclass: ou24PSF

    paths:
      sims_sed_library: /pscratch/sd/c/cmeldorf/rubin_sim_data/sims_sed_library
      sims_dir: /dvs_ro/cfs/cdirs/lsst/shared/external/roman-desc-sims/Roman_data
      output_dir: /pscratch/sd/c/cmeldorf/campari_out_dir
      debug_dir: /pscratch/sd/c/cmeldorf/campari_debug_dir
      lc_filetype: ecsv  # For production, this will be parquet. I just don't want to recreate all those files right now

    # OMG
    galsim:
      tds_file: /pscratch/sd/c/cmeldorf/campari/examples/perlmutter/tds_jupyter.yaml

    grid_options:
      type: contour
      percentiles:
      - 0
      - 88
      - 95
      - 100
      spacing: 0.50
      turn_grid_off: false

    simulations:
      avoid_non_linearity: false
      background_level: 0
      bg_gal_flux:
      - 10000
      - 100000
      - 1000000
      deltafcn_profile: false
      do_rotation: true
      do_xshift: true
      mismatch_seds: false
      noise: 50
      single_grid_point: false
      sim_galaxy_scale:
      - 1.0
      sim_galaxy_offset:
      - .00001414 # sqrt(2) * 1e-5
      base_pointing: 276
      base_sca: 10
      run_name: whatever


ou24psf:
  config_file: /pscratch/sd/c/cmeldorf/campari/examples/perlmutter/tds_jupyter.yaml

ou24:
  config_file: /pscratch/sd/c/cmeldorf/campari/examples/perlmutter/tds_jupyter.yaml
  sn_truth_dir: /dvs_ro/cfs/cdirs/lsst/www/DESC_TD_PUBLIC/Roman+DESC/PQ+HDF5_ROMAN+LSST_LARGE
  sims_sed_library: /pscratch/sd/c/cmeldorf/rubin_sim_data/sims_sed_library
  images:  /dvs_ro/cfs/cdirs/lsst/shared/external/roman-desc-sims/Roman_data/RomanTDS/images/simple_model
