photometry:
  campari:
    cutout_size: 11
    initial_flux_guess: 3000
    fetch_SED: true
    source_phot_ops: true
    use_roman: true
    weighting: true
    make_initial_guess: true
    method: lsqr
    pixel: false
    subtract_background: true
    use_real_images: true

    paths:
      sims_sed_library: /home/rubin_sim_data/sims_sed_library
      roman_path: /sims_dir
      sn_path: /snana_pq_dir
      sed_path: /campari_sed_dir
      output_dir: /campari_out_dir
      debug_dir: /campari_debug_dir

    # OMG
    galsim:
      tds_file: /campari/examples/perlmutter/tds.yaml

    grid_options:
      type: contour
      percentiles:
      - 0
      - 90
      - 98
      - 100
      spacing: 0.75
      turn_grid_off: false

    simulations:
      avoid_non_linearity: false
      background_level: 0
      bg_gal_flux:
      - 10000
      - 100000
      - 1000000
      check_perfection: false
      deltafcn_profile: false
      do_rotation: true
      do_xshift: true
      make_exact: false
      mismatch_seds: false
      noise: 50
      single_grid_point: false
      sim_galaxy_scale:
      - 1.0
      - 1.5
      sim_galaxy_offset:
      - .00001414 # sqrt(2) * 1e-5
      - .00002828 # sqrt(2) * 2e-5
      base_pointing: 276
      base_sca: 10

ou24:
  config_file: /sn_info_dir/tds.yaml
  sn_truth_dir: /snana_pq_dir
  sims_sed_library: /home/rubin_sim_data/sims_sed_library

ou24psf:
  config_file: /campari/examples/perlmutter/tds.yaml


