photometry:
  campari:
    cutout_size: 11
    initial_flux_guess: 3000
    fetch_SED: true
    source_phot_ops: true
    use_roman: true
    weighting: true
    make_initial_guess: true
    method: lsqr
    pixel: false
    subtract_background: true
    use_real_images: true

    paths:
      sims_sed_library: /hpc/home/cfm37/rubin_sim_data/sims_sed_library # CHANGE ME
      roman_path: /hpc/group/cosmology/OpenUniverse2024/
      sn_path: /hpc/group/cosmology/OpenUniverse2024/roman_rubin_cats_v1.1.2_faint/
      sed_path: /campari_sed_dir
      output_dir: /hpc/home/cfm37/campari_out # CHANGE ME
      debug_dir: /hpc/home/cfm37/campari_debug # CHANGE ME

    # OMG
    galsim:
      tds_file: /hpc/home/cfm37/MultiSMP/campari/temp_tds.yaml # CHANGE ME

    grid_options:
      type: contour
      percentiles:
      - 0
      - 90
      - 98
      - 100
      spacing: 0.75
      turn_grid_off: false

    simulations:
      avoid_non_linearity: false
      background_level: 0
      bg_gal_flux: 100000.0
      check_perfection: false
      deltafcn_profile: false
      do_rotation: true
      do_xshift: true
      make_exact: false
      mismatch_seds: false
      noise: 0
      sim_gal_dec_offset: 1e-5
      sim_gal_ra_offset: 1e-5
      single_grid_point: false

ou24:
  config_file: /hpc/home/cfm37/MultiSMP/campari/temp_tds.yaml # CHANGE ME
  sn_truth_dir: /hpc/group/cosmology/OpenUniverse2024/roman_rubin_cats_v1.1.2_faint/
  sims_sed_library: /hpc/home/cfm37/rubin_sim_data/sims_sed_library

ou24psf:
  config_file: /hpc/home/cfm37/MultiSMP/campari/temp_tds.yaml # CHANGE ME


